#import packages
library(GEOquery)
library(dtangle)
#library(hgu133plus2.db)
#library(AnnotationDbi)
library(limma)
library(ggplot2)
library(reshape2)
library(edgeR)
library(matrixStats)
library(dplyr)
library(tidyverse)
library(matrixStats)
library(broom)
library(knitr)
library(ggpubr)
library(biomaRt)
library(ggrepel)
library(patchwork)
library(ggsignif)
library(modelr)
library(cowplot)
library(gridExtra)
library(RColorBrewer)
library(markerGeneProfile) 
library(DESeq2)
library(factoextra)
library(PCAtools)

ref_final_common <- readRDS("/external/rprshnas01/netdata_kcni/stlab/Xiaolin/cell_deconv_data/data/MC_dtangle_ref_final_common.RData")
count_final_common <- readRDS("/external/rprshnas01/netdata_kcni/stlab/Xiaolin/cell_deconv_data/data/CMC_dtangle_count_final_common.RData")
#join the datasets
y <- cbind(ref_final_common, count_final_common)
#apply quantile normalization to these datasets in order to ensure that they are indeed comparable.
y <- normalizeQuantiles(y)
y <- t(y)
saveRDS(y, file="/external/rprshnas01/netdata_kcni/stlab/Xiaolin/cell_deconv_data/data/CMC_dtangle_y.RData")
#sbatch -J CMC_ddtangle_y --mem=4G -N 2 -t 0-1:0 -o /nethome/kcni/xzhou/cell_deconv/CMC_dtangle_y.slurm.log --wrap="Rscript /nethome/kcni/xzhou/dan_paper/CMC_dtangle_y.r"