---
title: "cmc_acc_mgp_analysis"
author: "Daniel Kiss"
date: "2/14/2024"
output: html_document
---

Packages etc.
```{r}
library(dplyr)
library(tidyverse)
library(edgeR)
library(markerGeneProfile) 
library(matrixStats)
library(cowplot)
library(broom)
library(knitr)
library(ggpubr)
library(biomaRt)
library(ggrepel)
library(patchwork)
library(ggsignif)
library(modelr)
library(ggbeeswarm)
library(lemon)
theme_set(theme_classic2())
#Colour palette
cbPalette = c("#56B4E9", "#009E73","#E69F00", "#0072B2", "#D55E00", "#CC79A7","#000000","#F0E442")
```


Load and format matrices
```{r}
CMC_ACC_matrix = read.csv("/external/rprshnas01/external_data/psychencode/PsychENCODE/CMC_ACC/RNA/CMC_ACC_count_matrix.csv") 
names(CMC_ACC_matrix) = gsub("X", '', names(CMC_ACC_matrix))
names(CMC_ACC_matrix)[1] = "gene_symbol"
#Rename EnsemblIDs to be compatible with gene names
CMC_ACC_matrix$gene_symbol = gsub("\\..*", '', CMC_ACC_matrix$gene_symbol)
CMC_ACC_matrix =  CMC_ACC_matrix %>% distinct(gene_symbol, .keep_all = TRUE)
#Make EnsemblIDs row names
row.names(CMC_ACC_matrix) = CMC_ACC_matrix$gene_symbol
CMC_ACC_matrix = CMC_ACC_matrix[,-1]

```


Load and format metadata
```{r}
psychencode_metadata = read.csv("//external/rprshnas01/external_data/psychencode/PsychENCODE/Metadata/CapstoneCollection_Metadata_Clinical.csv")
CMC_ACC_metadata = read.csv("/external/rprshnas01/external_data/psychencode/PsychENCODE/CMC_ACC/CMC_Human_rnaSeq_metadata_release6.csv") 
names(CMC_ACC_metadata)[names(CMC_ACC_metadata) == "Individual_ID"] = "individualID"
CMC_ACC_metadata = CMC_ACC_metadata %>% left_join(psychencode_metadata)
#Remove '+' from ageDeath for estimation/filtering
CMC_ACC_metadata$ageDeath = as.numeric(gsub("[+]", "", CMC_ACC_metadata$ageDeath))
#Create newStudy column for filtering
CMC_ACC_metadata = CMC_ACC_metadata %>%
  mutate(newStudy = case_when(
    individualIdSource == "MSSM"                    ~ "MSSM",
    individualIdSource == "Penn"                    ~ "Penn",
    individualIdSource == "Pitt"                    ~ "Pitt",
    TRUE                                            ~ "Not_Used"
  )) %>% filter(newStudy != "Not_Used")

```

Subset matrices based on study cohort
```{r}

#Create cohort specific matrices
mssm_samples = CMC_ACC_metadata %>% filter(newStudy == "MSSM") %>% pull(SampleID)
penn_samples = CMC_ACC_metadata %>% filter(newStudy == "Penn") %>% pull(SampleID)
pitt_samples = CMC_ACC_metadata %>% filter(newStudy == "Pitt") %>% pull(SampleID)
#Create matrices
gene_symbol = CMC_ACC_matrix$gene_symbol
mssm_matrix = CMC_ACC_matrix[, colnames(CMC_ACC_matrix) %in% mssm_samples] 
penn_matrix = CMC_ACC_matrix[, colnames(CMC_ACC_matrix) %in% penn_samples]
pitt_matrix = CMC_ACC_matrix[, colnames(CMC_ACC_matrix) %in% pitt_samples] 
```


Cell-Type Proportion Estimation: Updated marker list from Micaela's paper
```{r}
### GET MARKERS FOR MGP ANALYSIS
# note that this is the list of markers from micaela's paper - you get similar but diff results if you use the markers from the aging paper
sonny_markers = read_csv(url('https://raw.githubusercontent.com/sonnyc247/MarkerSelection/master/Data/Outputs/CSVs_and_Tables/Markers/MTG_and_CgG_lfct2/new_MTGnCgG_lfct2.5_Publication.csv'))
colnames(sonny_markers) = colnames(sonny_markers) %>% make.names() %>% tolower()

hgnc_mapping = read_tsv('/external/rprshnas01/kcni/dkiss/cell_prop_psychiatry/data/hgnc_complete_set.txt')

# now, this is the list of sonnys markers with entrez ids and ensembl ids where possible
sonny_hgnc_merged_markers = left_join(sonny_markers %>% dplyr::rename(entrez_id = entrez.gene.id), 
                                      hgnc_mapping %>% distinct(entrez_id, .keep_all = T)%>% 
                                        dplyr::select(entrez_id, ensembl_gene_id) %>% 
                                        dplyr::rename(ensembl_id = ensembl_gene_id)) %>% 
  dplyr::select(gene, entrez_id, ensembl_id, -ensembl.gene.id, everything()) %>% 
  group_by(subclass) %>% 
  arrange(subclass, -average.log.fold.change) %>% 
  ungroup()

# get ensembl list of markers
new_markers = sonny_hgnc_merged_markers %>% filter(used.in.mgp == "TRUE")
new_cell_types = new_markers %>% filter(!is.na(subclass)) %>% pull(subclass) %>% unique
new_marker_list  = lapply(new_cell_types, function(cell_type){
  cell_type_marker_list = new_markers %>% 
    filter(subclass == cell_type, ensembl_id %in% rownames(CMC_ACC_matrix)) %>% 
    pull(ensembl_id)
  return(cell_type_marker_list)
})
names(new_marker_list) = new_cell_types
print(new_cell_types)
```

Normalize and process count matrices and perform MGP analysis
```{r}
cell_types = new_marker_list$subclass %>% unique()

#Define vector of file names to perform MGP on and initialize empty variable before looping
matrix_names = c("mssm_matrix", "penn_matrix", "pitt_matrix")
mgp_estimations = setNames(data.frame(matrix(ncol = length(c(colnames(CMC_ACC_metadata), cell_types)), nrow = 0)), c(colnames(CMC_ACC_metadata), cell_types))

for(matrix_name in matrix_names) {
  #Preprocessing
  matrix = get(matrix_name)
  cpm = cpm(matrix, log = TRUE, prior.count = 0.1)
  sds = rowSds(cpm, na.rm = TRUE)
  matrix = cpm[sds > 0.1,] %>% as.data.frame() %>% rownames_to_column(var = "gene_symbol") #Consider setting SD cutoff to 0 
  genes_only = matrix %>% subset(gene_symbol != "")
if(length(which(duplicated(genes_only$gene_symbol))) != 0){
  genes_only = genes_only[-which(duplicated(genes_only$gene_symbol)),]
}

estimations = mgpEstimate(
  exprData = genes_only,
  genes = new_marker_list,
  geneColName = 'gene_symbol',
  outlierSampleRemove = F, # should outlier samples removed. This is done using boxplot stats
  geneTransform = NULL, # this is the default option for geneTransform
  groups = NULL, # if there are experimental groups provide them here. if not desired set to NULL
  seekConsensus = FALSE, # ensures gene rotations are positive in both of the groups
  removeMinority = F)

#Coerce estimations list into data frame 
estimations_scaled <- estimations$estimates %>% as.data.frame() %>% scale() %>% as.data.frame() %>% tibble::rownames_to_column(var = "SampleID")
estimations_metadata <- right_join(CMC_ACC_metadata, estimations_scaled, by = "SampleID")

#Merge cell type proportions with sample metadata
estimations_metadata = right_join(CMC_ACC_metadata, estimations_scaled )

mgp_estimations = rbind(mgp_estimations, estimations_metadata) 
}

write.csv(mgp_estimations, "/external/rprshnas01/kcni/dkiss/cell_prop_psychiatry/data/cmc_acc_mgp_estimations.csv")
```






